### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by zipotron** [f4pga/prjxray#2050]
Hello, I am trying to compile last version of the repo and I found a compilation error. I suspect there is a regression because one month ago I did compile successfully in another computer:
![xray](https://user-images.githubusercontent.com/6671137/202480081-e9325dec-cfb0-4f39-ae4d-d834562655ef.png)

**Comment by Matzikratzi** [comment]
I get the same error. I try compile on Ubuntu 22.10. Could it be that you used another distribution/version last time when it worked?
I do not have any computers with another OS, so I cannot check.

**Comment by Matzikratzi** [comment]
Probably duplicate to #1950

**Comment by Matzikratzi** [comment]
Yes, 'make build' works on Ubuntu 22.10 with this fix.
gcc 12.2.0-3ubuntu1

**Comment by zipotron** [comment]
Right! Is fix the issue! Thanks
